#!/bin/bash

confirm() {
	read -r -p "${1:-Are you sure? [y/N]} " response
	# case "$response" in
		# [yY][eE][sS][yY])
			# true
			# ;;
		# *)
			# false
			# ;;
	# esac
	if [[ $response == "y" || $response == "Y" || $response == "yes" || $response == "Yes" ]]
	then
		return 0;
	else
		return 1;
	fi
}

civ() {
  echo "Enjoy!"
  cd ~/.local/share/Steam/steamapps/common/Sid\ Meier\'s\ Civilization\ V
  ./Civ5XP &
  cd
}

confirm "Are you sure you want to play civ?" && 
confirm "Are you REALLY SURE??? You have better things to be doing..." &&
civ
