#!/bin/bash

if [ $# -gt 3 ] || [ $# -lt 2 ]; then
  echo "USAGE: syncdirs [--dry-run] DIRECTORY1 DIRECTORY2"
  exit 1
fi

# Test for flags
if [ $# -eq 3 ]; then
  if [ "$1" != "--dry-run" ]; then
  echo "USAGE: syncdirs [--dry-run] DIRECTORY1 DIRECTORY2"
  exit 1
  fi

  if [[ $2 == \/* ]]; then
    DIR1=$2
  else
    DIR1=$(pwd)/$2
  fi

  if [[ $3 == \/* ]]; then
    DIR2=$3
  else
    DIR2=$(pwd)/$3
  fi

  if [ ! -d "${DIR1}" ]; then
    echo "$DIR1 is not a directory"; exit 1;
  fi

  if [ ! -d "${DIR2}" ]; then
    echo "$DIR2 is not a directory"; exit 1;
  fi
  DRY_RUN=1
else
  if [[ $1 == \/* ]]; then
    DIR1=$1
  else
    DIR1=$(pwd)/$1
  fi

  if [[ $2 == \/* ]]; then
    DIR2=$2
  else
    DIR2=$(pwd)/$2
  fi
  DRY_RUN=0
fi

if [ ! -d "${DIR1}" ]
  then echo "$DIR1 is not a directory"; exit 1;
fi

if [ ! -d "${DIR2}" ]
  then echo "$DIR2 is not a directory"; exit 1;
fi

myfunction () {
  cd "$1"

  if [ -n "$(ls -A "${1}")" ]; then
    for f in *; do
      cd "$2"
      CP=0

      for target in *; do
        if [ "$target" == "$f" ]; then
          CP=1
          if [ -d "${1}/${f}" ]; then
            if [ -d "${2}/${f}" ]; then
              echo "Entering ${f}"
              myfunction "${1}/${f}" "${2}/${target}"
              echo "Exiting..."
              continue
            else
              echo "Can't Copy file to directory: Skipping ${f}"
              continue
            fi
          elif [ -d "${2}/${f}" ]; then
            echo "Can't Copy file to directory: Skipping ${f}"
            continue
          else
            if [ "$1/$f" -nt "$2/$target" ]; then
              echo
              echo "Copying ${f} from ${1} OVER ${f} in ${2}"
              if [ ${DRY_RUN} -eq 1 ]; then
                echo "cp $1/$f $2/$target"
              else
                cp "${1}/${f}" "${2}/${target}"
              fi
            else
              echo
              echo "Copying ${f} from ${2} OVER ${f} in ${1}"
              if [ ${DRY_RUN} -eq 1 ]; then
                echo "cp $2/$target $1/$f"
              else
                cp "${2}/${target}" "${1}/${f}"
              fi
            fi
          fi
        fi
      done

      if [ ${CP} -eq 0 ]; then
        echo
        echo "Copying ${f} from ${1} to ${2}"
        if [ ${DRY_RUN} -eq 1 ]; then
          if [ -d "${1}/${f}" ]; then
            echo "cp -r $1/$f $2/$f"
          else
            echo "cp $1/$f $2/$f"
          fi
        else
          if [ -d "${1}/${f}" ]; then
            cp -r "${1}/${f}" "${2}/${f}"
          else
            cp "${1}/${f}" "${2}/${f}"
          fi
        fi
      fi
    done
  fi

  cd "$2"
  if [ -n "$(ls -A "${2}")" ]; then
    for f in *; do
      cd "$1"
      FOUND=0

      for target in *; do
        if [ "$target" == "$f" ]; then
          FOUND=1
        fi
      done

      if [ ${FOUND} -eq 0 ]; then
        echo
        echo "Copying ${f} from ${2} to ${1}"
        if [ ${DRY_RUN} -eq 1 ]; then
          if [ -d "${2}/${f}" ]; then
            echo "cp -r $2/$f $1/$f"
          else
            echo "cp $2/$f $1/$f"
          fi
        else
          if [ -d "${2}/${f}" ]; then
            cp -r "${2}/${f}" "${1}/${f}"
          else
            cp "${2}/${f}" "${1}/${f}"
          fi
        fi
      fi
    done
  fi
}

myfunction "${DIR1}" "${DIR2}"
